[package]
authors = ["JaredSchifrien <Jared.Schifrien@gmail.com>"]
name = "client"
version = "0.1.0"

[dependencies]
cairo-rs = "^0"
cairo-sys-rs = "0.3.4"
glib = "^0"
glib-sys = "0.3.4"
gtk = "0.1.3"
hyper = "^0"
serde_json = "1.0"
serde_derive = "1.0.7"
serde = "1.0"