[package]
authors = ["JaredSchifrien <Jared.Schifrien@gmail.com>"]
name = "client"
version = "0.1.0"

[dependencies]
cairo-rs = "^0"
cairo-sys-rs = "0.3.4"
gdk = "^0"
gdk-pixbuf = "^0"
glib = "^0"
glib-sys = "0.3.4"
gtk = "0.1.3"
iron = "0.5.*"
router = "0.5.1"
rustc-serialize = "0.3.24"
